version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: canteen-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: canteen_ordering
      MYSQL_USER: canteen_user
      MYSQL_PASSWORD: canteen_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - canteen-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Backend Service
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: canteen-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/canteen_ordering?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: canteen_user
      SPRING_DATASOURCE_PASSWORD: canteen_password
      CORS_ALLOWED_ORIGINS: http://localhost:3000,http://localhost:3001
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - canteen-network
    restart: unless-stopped

  # Frontend Service
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: canteen-frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080
      NODE_ENV: production
    depends_on:
      - backend
    networks:
      - canteen-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  canteen-network:
    driver: bridge